/* Generated By:JJTree: Do not edit this line. ASTand_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.knowwe.timeline.parser;

public
class ASTand_op extends SimpleNode {
  public ASTand_op(int id) {
    super(id);
  }

  public ASTand_op(QueryLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public de.knowwe.timeline.Timeset jjtAccept(QueryLangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=10eaa1d3dffc7a5e6e4a84598486a0c5 (do not edit this line) */
