/* Generated By:JJTree: Do not edit this line. ASTquery.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.knowwe.timeline.parser;

public
class ASTquery extends SimpleNode {
  public ASTquery(int id) {
    super(id);
  }

  public ASTquery(QueryLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public de.knowwe.timeline.Timeset jjtAccept(QueryLangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ee82d05d6a0624086be3dde67705bda0 (do not edit this line) */
