/* Generated By:JJTree: Do not edit this line. ASTsimpleElement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.knowwe.timeline.parser;

import de.knowwe.timeline.tree.Comparators;
import de.knowwe.timeline.tree.Selectors;

public class ASTsimpleElement extends SimpleNode {
	public String question;
	public Selectors selector;
	public Comparators comp;
	public String compValue;

	public ASTsimpleElement(int id) {
		super(id);
	}

	public ASTsimpleElement(QueryLang p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	@Override
	public de.knowwe.timeline.Timeset jjtAccept(QueryLangVisitor visitor,
			Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=7010d1dbeb303a2533e1307efd6e7790 (do not edit this line) */
