/* Generated By:JJTree: Do not edit this line. ASTtimeFilter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.knowwe.timeline.parser;

import de.knowwe.timeline.tree.Comparators;
import de.knowwe.timeline.tree.TimeUnit;

public
class ASTtimeFilter extends SimpleNode {
	public Comparators comp;
	public double number;
	public TimeUnit unit;

	public ASTtimeFilter(int id) {
    super(id);
  }

  public ASTtimeFilter(QueryLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
	public de.knowwe.timeline.Timeset jjtAccept(QueryLangVisitor visitor,
			Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e1b0a49442162ba7993657af4337430d (do not edit this line) */
