/* Generated By:JavaCC: Do not edit this line. QueryLangTreeConstants.java Version 5.0 */
package de.knowwe.timeline.parser;

public interface QueryLangTreeConstants
{
  public int JJTQUERY = 0;
  public int JJTVOID = 1;
  public int JJTOR_OP = 2;
  public int JJTAND_OP = 3;
  public int JJTTIMEFILTER = 4;
  public int JJTSIMPLEELEMENT = 5;


  public String[] jjtNodeName = {
    "query",
    "void",
    "or_op",
    "and_op",
    "timeFilter",
    "simpleElement",
  };
}
/* JavaCC - OriginalChecksum=04e96a7f02a048e8840bd6ec7a5ede65 (do not edit this line) */
