/* Generated By:JJTree&JavaCC: Do not edit this line. QueryLangConstants.java */
package de.knowwe.timeline.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int FOR = 9;
  /** RegularExpression Id. */
  int INC = 10;
  /** RegularExpression Id. */
  int DEC = 11;
  /** RegularExpression Id. */
  int CNG = 12;
  /** RegularExpression Id. */
  int SGT = 13;
  /** RegularExpression Id. */
  int SLT = 14;
  /** RegularExpression Id. */
  int EQU = 15;
  /** RegularExpression Id. */
  int SGE = 16;
  /** RegularExpression Id. */
  int SLE = 17;
  /** RegularExpression Id. */
  int NEQ = 18;
  /** RegularExpression Id. */
  int OPEN_PAR = 19;
  /** RegularExpression Id. */
  int CLOSE_PAR = 20;
  /** RegularExpression Id. */
  int MSEC = 21;
  /** RegularExpression Id. */
  int SEC = 22;
  /** RegularExpression Id. */
  int MIN = 23;
  /** RegularExpression Id. */
  int HOUR = 24;
  /** RegularExpression Id. */
  int DAY = 25;
  /** RegularExpression Id. */
  int NUMBER = 26;
  /** RegularExpression Id. */
  int NAME = 27;
  /** RegularExpression Id. */
  int DIGITS = 28;
  /** RegularExpression Id. */
  int LETTER = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\\\\"",
    "\"\\t\"",
    "\" \"",
    "\"AND\"",
    "\"OR\"",
    "\"FOR\"",
    "\"\\\'increase\"",
    "\"\\\'decrease\"",
    "\"\\\'change\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "<NEQ>",
    "\"(\"",
    "\")\"",
    "<MSEC>",
    "<SEC>",
    "\"min\"",
    "\"h\"",
    "\"d\"",
    "<NUMBER>",
    "<NAME>",
    "<DIGITS>",
    "<LETTER>",
    "\";\"",
  };

}
