/* Generated By:JavaCC: Do not edit this line. QueryLangVisitor.java Version 5.0 */
package de.knowwe.timeline.parser;

public interface QueryLangVisitor
{
  public de.knowwe.timeline.Timeset visit(SimpleNode node, Object data);
  public de.knowwe.timeline.Timeset visit(ASTquery node, Object data);
  public de.knowwe.timeline.Timeset visit(ASTor_op node, Object data);
  public de.knowwe.timeline.Timeset visit(ASTand_op node, Object data);
  public de.knowwe.timeline.Timeset visit(ASTtimeFilter node, Object data);
  public de.knowwe.timeline.Timeset visit(ASTsimpleElement node, Object data);
}
/* JavaCC - OriginalChecksum=738df3f3956d3c1fdb85cce297fbac99 (do not edit this line) */
