/*
 * Copyright (C) 2010 University Wuerzburg, Computer Science VI
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package de.d3web.we.kdom;

/**
 * 
 * @author Jochen
 * @created 02.09.2010
 * 
 *          Interface providing a method to create a SectionID according to
 *          arbitrary conventions. Types can implement this
 *          interface. When Sections of this type are created they will be ask
 *          to specify the (last part of the) SectionID they want to attach to
 *          the section instead of the ID beeing auto-generated by the system.
 * 
 * 
 */
public interface SectionIDDeclarant {

	/**
	 * 
	 * return the (last part of the) new SectionID as String
	 * 
	 * @created 02.09.2010
	 * @param father
	 * @return
	 */
	public String createSectionID(Section<? extends Type> father);

}
